replicaCount: 1

image:
  repository: ghcr.io/jabronie0002/swiss
  tag: latest
  pullPolicy: IfNotPresent
  pullSecret: ghcr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 4004

namespace: swiss-dev

azureKeyVault:
  name: swiss-kv

secretProviderClass:
  enabled: false
  name: azure-kv-swiss
  keyvaultName: swiss-kv-01
  usePodIdentity: false
  secrets:
    - objectName: postgres-dbname
      objectType: secret
      key: dbname
    - objectName: postgres-password
      objectType: secret
      key: password
    - objectName: postgres-username
      objectType: secret
      key: username
  syncSecrets: true
  k8sSecretName: postgres-secrets