apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiss
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: swiss
  template:
    metadata:
      labels:
        app: swiss
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: swiss
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      
          ports:
            - containerPort: {{ .Values.service.targetPort }}