apiVersion: v1
kind: Service
metadata:
  name: swiss
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: swiss
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}